CREATE DATABASE;
USE DATABASE;
CREATE TABLE utilisateur(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE, 
    password VARCHAR(100) NOT NULL,
    dateCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) 